### menambahkan data user baru beserta dengan profilnya!
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "name": "Rifaldi",
    "email": "rifaldi88@gmail.com",
    "password": "Rifaldi88",
    "identityType": "KTP",
    "identityNumber": "12534235",
    "address": "Jl. Mawar no.10 Palembang"
}

### menampilkan daftar users!
GET http://localhost:3000/api/v1/users

### 'improvisasi' menampilkan detail informasi user dengan tampilan detail profilnya!
GET http://localhost:3000/api/v1/users-profile

### menampilkan detail informasi user dengan menampilkan juga profilnya!
GET http://localhost:3000/api/v1/users/1


### menambahkan akun baru ke user yang sudah didaftarkan!
POST http://localhost:3000/api/v1/account
Content-Type: application/json
 
{
    "user_id": 1,
    "bank_name": "BRI",
    "bank_account_number": "293846",
    "balance": 452333
}

### menampilkan daftar akun!
GET http://localhost:3000/api/v1/account

### 'improvisasi' menampilkan detail informasi akun dengan tampilan detail usernya!
GET http://localhost:3000/api/v1/account-profile

### menampilkan detail akun!
GET http://localhost:3000/api/v1/account/1


### mengirimkan uang dari 1 akun ke akun lain!
POST http://localhost:3000/api/v1/transaction
Content-Type: application/json
  
{
    "source_account_id": 1,
    "destination_account_id": 2,
    "amount": 824540
}
### menampilkan daftar transaksi!
GET http://localhost:3000/api/v1/transaction

### 'improvisasi' menampilkan daftar transasksi dengan tampilan akun dan usernya!
GET http://localhost:3000/api/v1/transaction-profile

### menampilkan detail transaksi dengan menampilkan pengirim dan penerimanya!
GET http://localhost:3000/api/v1/transaction/1




### register
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json


{
    "name": "regisrifaldi18",
    "email": "regisrifaldi18@gmail.com",
    "password": "Regisrifaldi18",
    "identityType": "KTP",
    "identityNumber": "182937658",
    "address": "Jl. Cemari no.08, Tangerang"
}

### login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json
 
{
    "email":"regisrifaldi18@gmail.com",
    "password":"Regisrifaldi18"
}

### authenticate
GET http://localhost:3000/api/v1/auth/authenticate
# Authorization: Bearer tokentoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsIm5hbWUiOiJyZWdpc3JpZmFsZGkxOCIsImVtYWlsIjoicmVnaXNyaWZhbGRpMThAZ21haWwuY29tIiwiaWF0IjoxNzEzNjMzOTM3fQ.2frXadgJvTIiINO9yp2snGkPzZuhWN2iwBKH8wWdbJg

